# version: "3.8"
# services:
#   mongodb:
#     image: mongo
#     container_name: mongodb
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=toor
#       - MONGO_INITDB_DATABASE=ecommerce
#     volumes:
#       - /home/barry/mongodb/database:/data/db
#       - ../queries:/queries
#     ports:
#       - 27017:27017
#     restart: unless-stopped
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asd456
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - 27017:27017
    volumes:
      - ../queries:/queries
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: asd456
      ME_CONFIG_MONGODB_URL: mongodb://root:asd456@mongo:27017/